//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIpaca_App.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AIpaca_App.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   API 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string apisetting {
            get {
                return ResourceManager.GetString("apisetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   앱버전과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string appversion {
            get {
                return ResourceManager.GetString("appversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   도전과제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string challenge {
            get {
                return ResourceManager.GetString("challenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다크모드과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string darkmode {
            get {
                return ResourceManager.GetString("darkmode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이메일과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   안녕하세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string hi {
            get {
                return ResourceManager.GetString("hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   홈과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   언어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string languageset {
            get {
                return ResourceManager.GetString("languageset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그아웃과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저사양모드과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lowspecmode {
            get {
                return ResourceManager.GetString("lowspecmode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   네트워크과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string network {
            get {
                return ResourceManager.GetString("network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비밀번호과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기록과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string record {
            get {
                return ResourceManager.GetString("record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로봇놈들과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string robots {
            get {
                return ResourceManager.GetString("robots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string setting {
            get {
                return ResourceManager.GetString("setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   회원가입과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string signup {
            get {
                return ResourceManager.GetString("signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시스템과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string system {
            get {
                return ResourceManager.GetString("system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   테마과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string thema {
            get {
                return ResourceManager.GetString("thema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   유저이름과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
    }
}
