//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIpaca_App.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AIpaca_App.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   업적 목록을 로드하는 데 실패했습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string achievement_load_failed {
            get {
                return ResourceManager.GetString("achievement_load_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   api키가 삭제되었습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string api_del_complete {
            get {
                return ResourceManager.GetString("api_del_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   API 요청 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string api_request_failed {
            get {
                return ResourceManager.GetString("api_request_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   API 요청 성공과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string api_request_successful {
            get {
                return ResourceManager.GetString("api_request_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   api키가 저장되었습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string api_save_complete {
            get {
                return ResourceManager.GetString("api_save_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   API 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string apisetting {
            get {
                return ResourceManager.GetString("apisetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   앱버전과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string appversion {
            get {
                return ResourceManager.GetString("appversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용자 인증 성공과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string authenticated_success {
            get {
                return ResourceManager.GetString("authenticated_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   백업과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string backup {
            get {
                return ResourceManager.GetString("backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   취소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   도전과제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string challenge {
            get {
                return ResourceManager.GetString("challenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   언어변경과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string changelanguage {
            get {
                return ResourceManager.GetString("changelanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   API 키를 삭제하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string check_api_del {
            get {
                return ResourceManager.GetString("check_api_del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   API 키를 저장하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string check_api_save {
            get {
                return ResourceManager.GetString("check_api_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서버 연결 확인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string checkserverconnection {
            get {
                return ResourceManager.GetString("checkserverconnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   복사 실패 : 복사할 텍스트가 없습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string copy_failed {
            get {
                return ResourceManager.GetString("copy_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   복사 완료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string copy_successful {
            get {
                return ResourceManager.GetString("copy_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   API 키 만들기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string createapikey {
            get {
                return ResourceManager.GetString("createapikey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다크 모드과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string darkmode {
            get {
                return ResourceManager.GetString("darkmode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DeepL 번역기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string deepltranslate {
            get {
                return ResourceManager.GetString("deepltranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이메일과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   영어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   에러과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   API 키 로드에 실패했습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string error_api_load_failed {
            get {
                return ResourceManager.GetString("error_api_load_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   API 응답이 유효하지 않습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string error_api_response {
            get {
                return ResourceManager.GetString("error_api_response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   API 키가 설정되지 않았습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string error_api_set {
            get {
                return ResourceManager.GetString("error_api_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   연결 오류과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string error_connection {
            get {
                return ResourceManager.GetString("error_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   네트워크 오류가 발생했습니다
        ///다시 시도해주세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string error_network {
            get {
                return ResourceManager.GetString("error_network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   API키가 설정되어 있지 않습니다
        ///설정 확인 바랍니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string error_no_api {
            get {
                return ResourceManager.GetString("error_no_api", resourceCulture);
            }
        }
        
        /// <summary>
        ///   텍스트 필드1 비어있습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string error_no_text1 {
            get {
                return ResourceManager.GetString("error_no_text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   텍스트 필드2 비어있습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string error_no_text2 {
            get {
                return ResourceManager.GetString("error_no_text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   평가받기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string evaluate {
            get {
                return ResourceManager.GetString("evaluate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   구글 번역기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string googletranslate {
            get {
                return ResourceManager.GetString("googletranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   안녕하세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string hi {
            get {
                return ResourceManager.GetString("hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   홈과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   한국어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ko {
            get {
                return ResourceManager.GetString("ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   언어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   언어 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string languageset {
            get {
                return ResourceManager.GetString("languageset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Libre Translate 번역기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string libretranslate {
            get {
                return ResourceManager.GetString("libretranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로딩중과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string log {
            get {
                return ResourceManager.GetString("log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그아웃과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저사양 모드과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lowspecmode {
            get {
                return ResourceManager.GetString("lowspecmode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수동 업데이트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string manualupdate {
            get {
                return ResourceManager.GetString("manualupdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   네트워크과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string network {
            get {
                return ResourceManager.GetString("network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   앱의 새로운 버전이 있습니다.
        ///업데이트가 필요합니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string newupdate {
            get {
                return ResourceManager.GetString("newupdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   확인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   원문과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string originaltext {
            get {
                return ResourceManager.GetString("originaltext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파파고 번역기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string papagotranslate {
            get {
                return ResourceManager.GetString("papagotranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비밀번호과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   평가과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string rating {
            get {
                return ResourceManager.GetString("rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   추천번역과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string recommend {
            get {
                return ResourceManager.GetString("recommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   추천번역과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string recommendedtext {
            get {
                return ResourceManager.GetString("recommendedtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기록과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string record {
            get {
                return ResourceManager.GetString("record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   레코드 추가에 실패했습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string record_addition_failed {
            get {
                return ResourceManager.GetString("record_addition_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   요청시간과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string requesttime {
            get {
                return ResourceManager.GetString("requesttime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로봇놈들과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string robots {
            get {
                return ResourceManager.GetString("robots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   점수과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string score {
            get {
                return ResourceManager.GetString("score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   언어 선택과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string selectlanguage {
            get {
                return ResourceManager.GetString("selectlanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string setting {
            get {
                return ResourceManager.GetString("setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   회원가입과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string signup {
            get {
                return ResourceManager.GetString("signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   회원가입 성공과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string signup_successful {
            get {
                return ResourceManager.GetString("signup_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   앱 버전 확인중과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string splash_check_version {
            get {
                return ResourceManager.GetString("splash_check_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   앱스토어를 열지 못했습니다
        ///업데이트 내용을 수동으로 확인하십시오과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string splash_error_appstore {
            get {
                return ResourceManager.GetString("splash_error_appstore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   앱 버전 확인 오류과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string splash_error_appversion {
            get {
                return ResourceManager.GetString("splash_error_appversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서버 연결 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string splash_server_connect_failed {
            get {
                return ResourceManager.GetString("splash_server_connect_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서버 연결 성공 - 횟수과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string splash_server_connect_success {
            get {
                return ResourceManager.GetString("splash_server_connect_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서버 연결중 - 횟수과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string splash_server_try_connect {
            get {
                return ResourceManager.GetString("splash_server_try_connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   최신버전입니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string splash_version_latest {
            get {
                return ResourceManager.GetString("splash_version_latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   성공과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시스템과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string system {
            get {
                return ResourceManager.GetString("system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   번역할 텍스트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string text_to_be_translated {
            get {
                return ResourceManager.GetString("text_to_be_translated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   테마과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string theme {
            get {
                return ResourceManager.GetString("theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   번역된 텍스트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string translated_text {
            get {
                return ResourceManager.GetString("translated_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   번역문과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string translatedtext {
            get {
                return ResourceManager.GetString("translatedtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   번역과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string translation {
            get {
                return ResourceManager.GetString("translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   업데이트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   유저이름과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
    }
}
